/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Camp Site.glb -o src/components/campsite.jsx -k -K -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/Camp Site.glb')
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh name="group1032316131" geometry={nodes.group1032316131.geometry} material={materials.mat12} />
        <mesh name="group1967547015" geometry={nodes.group1967547015.geometry} material={materials.mat12} />
        <mesh name="group369628133" geometry={nodes.group369628133.geometry} material={materials.mat14} />
        <mesh name="group814213027" geometry={nodes.group814213027.geometry} material={materials.mat13} />
        <mesh name="group1016917409" geometry={nodes.group1016917409.geometry} material={materials.mat12} />
        <mesh name="group43999202" geometry={nodes.group43999202.geometry} material={materials.mat15} />
        <mesh name="group361724352" geometry={nodes.group361724352.geometry} material={materials.mat14} />
        <mesh name="group1290389257" geometry={nodes.group1290389257.geometry} material={materials.mat17} />
        <mesh name="group1710131328" geometry={nodes.group1710131328.geometry} material={materials.mat14} />
        <mesh name="group971618157" geometry={nodes.group971618157.geometry} material={materials.mat17} />
        <mesh name="group1938999627" geometry={nodes.group1938999627.geometry} material={materials.mat17} />
        <mesh name="group438287929" geometry={nodes.group438287929.geometry} material={materials.mat17} />
        <mesh name="group839141860" geometry={nodes.group839141860.geometry} material={materials.mat20} />
        <mesh name="group681693235" geometry={nodes.group681693235.geometry} material={materials.mat12} />
        <mesh name="group546474264" geometry={nodes.group546474264.geometry} material={materials.mat12} />
        <mesh name="group444127645" geometry={nodes.group444127645.geometry} material={materials.mat20} />
        <mesh name="group628543853" geometry={nodes.group628543853.geometry} material={materials.mat13} />
        <mesh name="group1258552803" geometry={nodes.group1258552803.geometry} material={materials.mat14} />
        <mesh name="group825829655" geometry={nodes.group825829655.geometry} material={materials.mat17} />
        <mesh name="group819088452" geometry={nodes.group819088452.geometry} material={materials.mat17} />
        <mesh name="group57659713" geometry={nodes.group57659713.geometry} material={materials.mat17} />
        <mesh name="group80932093" geometry={nodes.group80932093.geometry} material={materials.mat17} />
        <mesh name="group1068871216" geometry={nodes.group1068871216.geometry} material={materials.mat17} />
        <mesh name="group1178884629" geometry={nodes.group1178884629.geometry} material={materials.mat17} />
        <mesh name="group439549591" geometry={nodes.group439549591.geometry} material={materials.mat14} />
        <mesh name="group226959944" geometry={nodes.group226959944.geometry} material={materials.mat14} />
        <mesh name="group1103103526" geometry={nodes.group1103103526.geometry} material={materials.mat14} />
        <mesh name="group2130870490" geometry={nodes.group2130870490.geometry} material={materials.mat12} />
        <mesh name="group2032640420" geometry={nodes.group2032640420.geometry} material={materials.mat14} />
        <mesh name="group476880120" geometry={nodes.group476880120.geometry} material={materials.mat14} />
        <mesh name="group1138068695" geometry={nodes.group1138068695.geometry} material={materials.mat20} />
        <mesh name="group1292612855" geometry={nodes.group1292612855.geometry} material={materials.mat10} />
        <mesh name="group257749776" geometry={nodes.group257749776.geometry} material={materials.mat17} />
        <mesh name="group784294784" geometry={nodes.group784294784.geometry} material={materials.mat13} />
        <mesh name="group1567315581" geometry={nodes.group1567315581.geometry} material={materials.mat13} />
        <mesh name="group326174911" geometry={nodes.group326174911.geometry} material={materials.mat13} />
        <mesh name="group1428101929" geometry={nodes.group1428101929.geometry} material={materials.mat20} />
        <group name="group382900854">
          <mesh name="mesh382900854" geometry={nodes.mesh382900854.geometry} material={materials.mat13} />
          <mesh name="mesh382900854_1" geometry={nodes.mesh382900854_1.geometry} material={materials.mat17} />
        </group>
        <mesh name="group907185404" geometry={nodes.group907185404.geometry} material={materials.mat20} />
        <mesh name="group2123952850" geometry={nodes.group2123952850.geometry} material={materials.mat20} />
        <mesh name="group301545879" geometry={nodes.group301545879.geometry} material={materials.mat20} />
        <mesh name="group311075704" geometry={nodes.group311075704.geometry} material={materials.mat20} />
        <mesh name="group824841406" geometry={nodes.group824841406.geometry} material={materials.mat20} />
        <mesh name="group1197429230" geometry={nodes.group1197429230.geometry} material={materials.mat20} />
        <mesh name="group1591894839" geometry={nodes.group1591894839.geometry} material={materials.mat20} />
        <mesh name="group1317986196" geometry={nodes.group1317986196.geometry} material={materials.mat20} />
        <mesh name="group1871995632" geometry={nodes.group1871995632.geometry} material={materials.mat20} />
        <mesh name="group1114838022" geometry={nodes.group1114838022.geometry} material={materials.mat17} />
        <group name="group1660017390">
          <mesh name="mesh1660017390" geometry={nodes.mesh1660017390.geometry} material={materials.mat17} />
          <mesh name="mesh1660017390_1" geometry={nodes.mesh1660017390_1.geometry} material={materials.mat13} />
        </group>
        <mesh name="group1944889744" geometry={nodes.group1944889744.geometry} material={materials.mat12} />
        <mesh name="group1350252339" geometry={nodes.group1350252339.geometry} material={materials.mat13} />
        <mesh name="group921886382" geometry={nodes.group921886382.geometry} material={materials.mat12} />
        <mesh name="group194689076" geometry={nodes.group194689076.geometry} material={materials.mat12} />
        <mesh name="group324380574" geometry={nodes.group324380574.geometry} material={materials.mat20} />
        <mesh name="group929167590" geometry={nodes.group929167590.geometry} material={materials.mat17} />
        <mesh name="group2006498187" geometry={nodes.group2006498187.geometry} material={materials.mat23} />
        <mesh name="group400478635" geometry={nodes.group400478635.geometry} material={materials.mat23} />
        <group name="group651326417">
          <mesh name="mesh651326417" geometry={nodes.mesh651326417.geometry} material={materials.mat23} />
          <mesh name="mesh651326417_1" geometry={nodes.mesh651326417_1.geometry} material={materials.mat20} />
        </group>
        <group name="group1540635957">
          <mesh name="mesh1540635957" geometry={nodes.mesh1540635957.geometry} material={materials.mat20} />
          <mesh name="mesh1540635957_1" geometry={nodes.mesh1540635957_1.geometry} material={materials.mat23} />
        </group>
        <group name="group1630839489">
          <mesh name="mesh1630839489" geometry={nodes.mesh1630839489.geometry} material={materials.mat20} />
          <mesh name="mesh1630839489_1" geometry={nodes.mesh1630839489_1.geometry} material={materials.mat23} />
        </group>
        <group name="group807031823">
          <mesh name="mesh807031823" geometry={nodes.mesh807031823.geometry} material={materials.mat20} />
          <mesh name="mesh807031823_1" geometry={nodes.mesh807031823_1.geometry} material={materials.mat23} />
        </group>
        <group name="group39266399">
          <mesh name="mesh39266399" geometry={nodes.mesh39266399.geometry} material={materials.mat20} />
          <mesh name="mesh39266399_1" geometry={nodes.mesh39266399_1.geometry} material={materials.mat23} />
        </group>
        <group name="group778519827">
          <mesh name="mesh778519827" geometry={nodes.mesh778519827.geometry} material={materials.mat20} />
          <mesh name="mesh778519827_1" geometry={nodes.mesh778519827_1.geometry} material={materials.mat23} />
        </group>
        <group name="group189035796">
          <mesh name="mesh189035796" geometry={nodes.mesh189035796.geometry} material={materials.mat21} />
          <mesh name="mesh189035796_1" geometry={nodes.mesh189035796_1.geometry} material={materials.mat10} />
        </group>
        <group name="group1529860242">
          <mesh name="mesh1529860242" geometry={nodes.mesh1529860242.geometry} material={materials.mat10} />
          <mesh name="mesh1529860242_1" geometry={nodes.mesh1529860242_1.geometry} material={materials.mat21} />
        </group>
        <group name="group1698260185">
          <mesh name="mesh1698260185" geometry={nodes.mesh1698260185.geometry} material={materials.mat21} />
          <mesh name="mesh1698260185_1" geometry={nodes.mesh1698260185_1.geometry} material={materials.mat10} />
        </group>
        <group name="group2144833775">
          <mesh name="mesh2144833775" geometry={nodes.mesh2144833775.geometry} material={materials.mat21} />
          <mesh name="mesh2144833775_1" geometry={nodes.mesh2144833775_1.geometry} material={materials.mat10} />
        </group>
        <group name="group2098336265">
          <mesh name="mesh2098336265" geometry={nodes.mesh2098336265.geometry} material={materials.mat21} />
          <mesh name="mesh2098336265_1" geometry={nodes.mesh2098336265_1.geometry} material={materials.mat10} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Camp Site.glb')


export default  Model 