/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/f35_fighter_jet.glb
Author: Spentza_93 (https://sketchfab.com/Spentza93)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/f35-fighter-jet-084369d3fddc480080cfb05364d75a46
Title: F35 fighter Jet
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

 function F35(props)  {
  const { nodes, materials } = useGLTF('f35_fighter_jet.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.06}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, Math.PI]} scale={[100, 100, 13.31]}>
            <mesh geometry={nodes.Cube_Material_0.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_1.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_2.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_3.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_4.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_5.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_6.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_7.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_8.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_9.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_10.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_11.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_12.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_13.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_14.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_15.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_16.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_17.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_18.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_19.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_20.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_21.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_22.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_23.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_24.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_25.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_26.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_27.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_28.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_29.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_30.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_31.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_32.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_33.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material_0_34.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material004_0.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Cube_Material004_0_1.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Cube_Material004_0_2.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Cube_Material001_0.geometry} material={materials['Material.001']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('public/models/f35_fighter_jet.glb')

export default F35


//make model a clone that keeps reappearing in the scene at random locations and random sizes

