/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/Soldier.glb -o src/components/soldier.jsx -k -K -r public 
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Soldier.glb')
  console.log(animations);
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    if (actions.run) {
      actions.run.play();
    }
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Armature">
            <primitive object={nodes.hips} />
            <primitive object={nodes.kneeIKL} />
            <primitive object={nodes.ellbowIKL} />
            <primitive object={nodes.wristIKL} />
            <primitive object={nodes.kneeIKR} />
            <primitive object={nodes.ellbowIKR} />
            <primitive object={nodes.wristIKR} />
            <primitive object={nodes.ankleIKL} />
            <primitive object={nodes.ankleIKR} />
          </group>
          <skinnedMesh name="M4_Amo" geometry={nodes.M4_Amo.geometry} material={materials['Material.001']} skeleton={nodes.M4_Amo.skeleton} position={[-20.538, 22.989, -1.293]} rotation={[0.006, -0.106, -1.511]} scale={19.555} />
          <skinnedMesh name="M4" geometry={nodes.M4.geometry} material={materials['Material.001']} skeleton={nodes.M4.skeleton} position={[-20.484, 22.996, 1.314]} rotation={[0.006, -0.106, -1.511]} scale={19.555} />
          <group name="Soldat" rotation={[-Math.PI / 2, 0, 0]} scale={[20.911, 20.389, 20.168]}>
            <skinnedMesh name="Soldat_1" geometry={nodes.Soldat_1.geometry} material={materials['Characters_For_Andrew:lambert']} skeleton={nodes.Soldat_1.skeleton} />
            <skinnedMesh name="Soldat_2" geometry={nodes.Soldat_2.geometry} material={materials['Material.001']} skeleton={nodes.Soldat_2.skeleton} />
            <skinnedMesh name="Soldat_3" geometry={nodes.Soldat_3.geometry} material={materials['Material.003']} skeleton={nodes.Soldat_3.skeleton} />
            <skinnedMesh name="Soldat_4" geometry={nodes.Soldat_4.geometry} material={materials['Material.002']} skeleton={nodes.Soldat_4.skeleton} />
            <skinnedMesh name="Soldat_5" geometry={nodes.Soldat_5.geometry} material={materials['Material.004']} skeleton={nodes.Soldat_5.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Soldier.glb')

export default Model
